
name: CI2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:

    permissions: write-all
    name: print-token
    environment: dev 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
       sudo apt-get install jq
       sudo apt-get install zip gzip tar
       mkdir bign
       chmod +x ./scrpt.sh
       ./scrpt.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: irixHDD
        path: ${{github.workspace}}/bign



        
