name: CIk2
on:
  workflow_dispatch:
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:


    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
       pip install -r requirements.txt 
       cd bign
       python3 gofile.py url.txt
       cd ..
       Compress-Archive bign bign.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: irixHDD
        path: ${{github.workspace}}/bign.zip



        
