
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
          sudo add-apt-repository ppa:c.falco/mame
          sudo apt-get update
          sudo apt-get install mame-tools
          sudo apt-get install unzip
          wget -O 64.zip https://archive.org/download/ultra-64-2-gig-scsi-irix-53-confirmed-2/ULTRA64_2GIG_SCSI_IRIX53_confirmed2.zip
          unzip 64.zip
          ls
          cd 64
          mv "ULTRA64_2GIG_SCSI_IRIX53_confirmed2.img" "n64.img"
          chdman createhd -i "n64.img" -o "n64.chd" -c none -f
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: irixHDD
        path: ${{github.workspace}}/64/n64,chd
