
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:

    permissions: write-all
    name: print-token
    environment: dev 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
          sudo apt-get update
          wget -mpEk --wait 4 "http://www.netyaroze-europe.com/cgi-bin/homepage/listsceehome.cgi"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Yaroze
        path: ${{github.workspace}}


    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.9.0
      with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: ${{github.workspace}}
        
